// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/calendar": {
            "get": {
                "description": "黄历查询",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "黄历相关"
                ],
                "summary": "黄历查询",
                "parameters": [
                    {
                        "type": "string",
                        "description": "日期：例如：2020-11-11",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "2000": {
                        "description": "黄历详情",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseCalendar"
                        }
                    }
                }
            }
        },
        "/calendar/auspicious": {
            "get": {
                "description": "择吉日查询",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "黄历相关"
                ],
                "summary": "择吉日查询",
                "parameters": [
                    {
                        "type": "string",
                        "example": "month",
                        "description": "时间范围(必填) week:1周, month:1月, month3:3月, year:1年",
                        "name": "dur",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "结婚",
                        "description": "名称(必填)",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "页数(选填)    默认:1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 20,
                        "description": "条数(选填)    默认:20",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "yi",
                        "description": "类型(必填) yi:宜,ji:忌",
                        "name": "type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "example": true,
                        "description": "是否只看周末(选填) 1:是，0:否，默认:0",
                        "name": "weekend",
                        "in": "query"
                    }
                ],
                "responses": {
                    "2000": {
                        "description": "吉日列表",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseAuspicious"
                        }
                    }
                }
            }
        },
        "/fortune": {
            "get": {
                "description": "星座运势查询",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "星座相关"
                ],
                "summary": "星座运势查询",
                "parameters": [
                    {
                        "type": "string",
                        "example": "2020-11-11",
                        "description": "日期(必填)",
                        "name": "date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "baiyang",
                        "description": "星座(必填)",
                        "name": "star",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "时间(选填) 默认获取5个时间信息",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "2001": {
                        "description": "获取星座某时间段运势",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseOneFortune"
                        }
                    },
                    "2002": {
                        "description": "获取星座所有时间段运势",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseAllFortune"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller._ResponseAllFortune": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "type": "object",
                    "$ref": "#/definitions/model.AllModel"
                },
                "msg": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "controller._ResponseAuspicious": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CalendarModel"
                    }
                },
                "msg": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "controller._ResponseCalendar": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "type": "object",
                    "$ref": "#/definitions/model.CalendarModel"
                },
                "msg": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "controller._ResponseOneFortune": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "type": "object",
                    "$ref": "#/definitions/model.OneModel"
                },
                "msg": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "model.AllModel": {
            "type": "object",
            "properties": {
                "month": {
                    "description": "本年运势",
                    "type": "object",
                    "$ref": "#/definitions/model.OneModel"
                },
                "today": {
                    "description": "今日运势",
                    "type": "object",
                    "$ref": "#/definitions/model.OneModel"
                },
                "tomorrow": {
                    "description": "明日运势",
                    "type": "object",
                    "$ref": "#/definitions/model.OneModel"
                },
                "week": {
                    "description": "本周运势",
                    "type": "object",
                    "$ref": "#/definitions/model.OneModel"
                },
                "year": {
                    "type": "object",
                    "$ref": "#/definitions/model.OneModel"
                }
            }
        },
        "model.CalendarModel": {
            "type": "object",
            "properties": {
                "caishen": {
                    "description": "财神",
                    "type": "string"
                },
                "chong": {
                    "description": "冲",
                    "type": "string"
                },
                "date": {
                    "description": "日期",
                    "type": "string"
                },
                "days": {
                    "description": "还有几天",
                    "type": "integer"
                },
                "emonth": {
                    "description": "英文月",
                    "type": "string"
                },
                "eweek": {
                    "description": "英文周",
                    "type": "string"
                },
                "fushen": {
                    "description": "福神",
                    "type": "string"
                },
                "ji": {
                    "description": "忌",
                    "type": "string"
                },
                "jiri": {
                    "description": "吉日",
                    "type": "string"
                },
                "jishenyiqu": {
                    "description": "吉神宜趋",
                    "type": "string"
                },
                "nongli": {
                    "description": "农历",
                    "type": "string"
                },
                "sha": {
                    "description": "煞",
                    "type": "string"
                },
                "shengxiao": {
                    "description": "生肖",
                    "type": "string"
                },
                "star": {
                    "description": "星座",
                    "type": "string"
                },
                "suici": {
                    "description": "岁次",
                    "type": "string"
                },
                "taishen": {
                    "description": "胎神",
                    "type": "string"
                },
                "week": {
                    "description": "中文周",
                    "type": "string"
                },
                "wuxing": {
                    "description": "五行",
                    "type": "string"
                },
                "xiongshen": {
                    "description": "凶神",
                    "type": "string"
                },
                "xishen": {
                    "description": "喜神",
                    "type": "string"
                },
                "yangli": {
                    "description": "阳历",
                    "type": "string"
                },
                "yi": {
                    "description": "宜",
                    "type": "string"
                },
                "zhiri": {
                    "description": "值日",
                    "type": "string"
                }
            }
        },
        "model.OneModel": {
            "type": "object",
            "properties": {
                "career": {
                    "description": "工作运势",
                    "type": "string"
                },
                "color": {
                    "description": "幸运颜色",
                    "type": "string"
                },
                "health": {
                    "description": "健康运势",
                    "type": "string"
                },
                "love": {
                    "description": "爱情运势",
                    "type": "string"
                },
                "money": {
                    "description": "财运运势",
                    "type": "string"
                },
                "number": {
                    "description": "幸运数字",
                    "type": "string"
                },
                "presummary": {
                    "description": "概述",
                    "type": "string"
                },
                "star": {
                    "description": "贵人星座",
                    "type": "string"
                },
                "summary": {
                    "description": "综合运势",
                    "type": "string"
                }
            }
        },
        "model.ParamAuspiciousList": {
            "type": "object",
            "required": [
                "dur",
                "name",
                "type"
            ],
            "properties": {
                "dur": {
                    "description": "时间范围(必填) week:1周, month:1月, month3:3月, year:1年",
                    "type": "string",
                    "example": "month"
                },
                "name": {
                    "description": "名称(必填)",
                    "type": "string",
                    "example": "结婚"
                },
                "page": {
                    "description": "页数(选填)    默认:1",
                    "type": "integer",
                    "example": 1
                },
                "size": {
                    "description": "条数(选填)    默认:20",
                    "type": "integer",
                    "example": 20
                },
                "type": {
                    "description": "类型(必填) yi:宜,ji:忌",
                    "type": "string",
                    "example": "yi"
                },
                "weekend": {
                    "description": "是否只看周末(选填) 1:是，0:否，默认:0",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "model.ParamStar": {
            "type": "object",
            "required": [
                "date",
                "star"
            ],
            "properties": {
                "date": {
                    "description": "日期(必填)",
                    "type": "string",
                    "example": "2020-11-11"
                },
                "star": {
                    "description": "星座(必填)",
                    "type": "string",
                    "example": "baiyang"
                },
                "type": {
                    "description": "时间(选填) 默认获取5个时间信息",
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "192.168.3.180:8082",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "玄学宝典",
	Description: "玄学宝典接口文档",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
